# Generated by Django 4.2.7 on 2023-11-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='registrated',
            field=models.BooleanField(default=True),
        ),
    ]
