# Generated by Django 4.2.7 on 2023-11-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_payment_pay_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_code',
            field=models.CharField(max_length=50),
        ),
    ]
